version: '3.8'

services:
  beui-mysql:
    image: mysql:8.0
    container_name: beui-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: greenteashop
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - beui-network
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql-init
    depends_on:
      beui-sqlserver:
        condition: service_healthy
    volumes:
      - ./src/main/resources/create_tables.sql:/sql/init.sql:ro
    entrypoint: ["/bin/bash", "-c", "sleep 20 && /opt/mssql-tools/bin/sqlcmd -S beui-sqlserver -U sa -P YourStrong@Password1 -i /sql/init.sql"]
    networks:
      - beui-network
    command: >
      bash -c "
        echo '[Init] Waiting 10s for SQL Server...' 
        sleep 15
        echo '[Init] Running SQL init script...'
        /opt/mssql-tools/bin/sqlcmd -S beui-sqlserver -U sa -P YourStrong@Password1 -i /sql/init.sql
        echo '[Init] Done.'
      "
    restart: "no"

  greentea-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greentea-app
    depends_on:
      beui-sqlserver:
        condition: service_healthy
      sql-init:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://beui-sqlserver:1433;databaseName=greenteashop;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Password1
    ports:
      - "8080:8080"
    volumes:
      - ./uploads/images:/app/uploads/images
    networks:
      - beui-network

volumes:
  mysql-data:

networks:
  beui-network:
    driver: bridge
    