version: '3.8'

services:
  beui-sqlserver:
    image: nthquyen1904/sqlserver-greenteashop:latest  # Registry: nthquyen1904
    container_name: beui-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password1
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - beui-network
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver-data:

networks:
  beui-network:
    driver: bridge 