version: '3.8'

services:
  beui-mysql:
    image: mysql:8.0
    container_name: beui-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: greenteashop
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/create_tables.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - beui-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pyour_mysql_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  greentea-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greentea-app
    depends_on:
      beui-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://beui-mysql:3306/greenteashop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=appuser_password
    ports:
      - "8080:8080"
    volumes:
      - ./uploads/images:/app/uploads/images
    networks:
      - beui-network

volumes:
  mysql-data:

networks:
  beui-network:
    driver: bridge