version: '3.8'

services:
  beui-mysql:
    image: mysql:8.0
    container_name: beui-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: greenteashop
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - beui-network
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  beui-network:
    driver: bridge 