#spring:
#  application:
#    name: ecommerceApp
#  datasource:
#    url: jdbc:mysql://localhost:3306/greenteashop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
#    username: greentea_user
#    password: greentea_pass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    cache: false
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        connection:
#          characterEncoding: UTF-8
#          useUnicode: true
#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#
## Server Configuration
#server:
#  port: 8080
#
## File Upload Configuration
#upload:
#  dir: uploads/images
#
## Logging Configuration
#logging:
#  level:
#    org.springframework.jdbc: INFO
#    org.hibernate.SQL: INFO
#    com.beui.ecommerceApp: DEBUG