spring:
  application:
    name: ecommerceApp
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/greenteashop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          characterEncoding: UTF-8
          useUnicode: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  upload:
    path: ${APP_UPLOAD_PATH:/app/uploads/images}

server:
  port: ${SERVER_PORT:8080}

